name: dev Redis unix.sock

on:
  workflow_dispatch:

jobs:
  test-dev-Redis-unix-sock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install prerequisites for puppeteer tests
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y
          google-chrome --version
          python3 --version
          pip3 --version
          node -v
          npm -v

          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan git.onlyoffice.com >> ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone git@git.onlyoffice.com:ONLYOFFICE-QA/Dep.Tests.git
          cd Dep.Tests
          sed -i 's/url=https:\/\/github.com\/ONLYOFFICE-data\/pp-files.git/url = git@github.com:ONLYOFFICE-data\/pp-files.git/' .gitmodules
          git submodule update --init puppeteer/files
          cd puppeteer/engine
          npm install
          cp ../config_chrome_linux.json ../config_chrome_linux.json.bak

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Change EC2_IP on the PROXY
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.234.188.198 << 'EOF'
          sudo sed -i "s/server [0-9.:]*;/server 127.0.0.1:8080;/" /etc/nginx/sites-enabled/oods_default_and_ds-vpath
          sudo systemctl reload nginx
          head /etc/nginx/sites-enabled/oods_default_and_ds-vpath
          EOF

      - name: Docker run ONLYOFFICE-Docs EE for test REDIS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.234.188.198 << 'EOF'
          sudo docker pull onlyoffice/4testing-documentserver-ee:${{ vars.ONLYOFFICE_VERSION }}.${{ vars.ONLYOFFICE_BUILD }}
          sudo docker run -itd -p 8080:80 -e WOPI_ENABLED=true --name ds-ee-dev onlyoffice/4testing-documentserver-ee:${{ vars.ONLYOFFICE_VERSION }}.${{ vars.ONLYOFFICE_BUILD }}
          sleep 120
          sudo docker exec ds-ee-dev supervisorctl start all
          echo "-------------------------------------"
          curl -s https://oods.div-proxy.qa-onlyoffice.net/healthcheck
          echo "-------------------------------------"
          EOF

      - name: Info about installed Package, must be ONLYOFFICE-Docs EE
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.234.188.198 << 'EOF'
          echo "Installed packages:"
          echo "-------------------------------------"
          sudo docker exec ds-ee-dev dpkg-query -l | grep onlyoffice-documentserver
          echo "-------------------------------------"
          echo "api.js from server:"
          echo "-------------------------------------"
          sudo docker exec ds-ee-dev curl -s http://127.0.0.1/web-apps/apps/api/documents/api.js | head -n 10
          echo "-------------------------------------"
          echo "info.json from server(packageType must be 1):"
          echo "-------------------------------------"
          sudo docker exec ds-ee-dev curl -s http://127.0.0.1:8000/info/info.json | jq | grep -i -e buildVersion -e buildNumber -e packageType
          echo "-------------------------------------"
          echo "check WOPI enabled(must be data except 404 Not Found):"
          echo "-------------------------------------"
          output=$(curl -s http://127.0.0.1:8080/hosting/discovery)
          if echo "$output" | grep -q 'value='; then
            echo "$output" | grep -o 'value="[^"]*"' | head -n 5 | cut -c1-100
          else
            echo "$output"
          fi
          echo "-------------------------------------"
          echo "check WOPI HTTPS(must be data except 404 Not Found):"
          echo "-------------------------------------"
          output=$(curl -s https://oods.div-proxy.qa-onlyoffice.net/hosting/discovery)
          if echo "$output" | grep -q 'value='; then
            echo "$output" | grep -o 'value="[^"]*"' | head -n 5 | cut -c1-100
          else
            echo "$output"
          fi
          echo "-------------------------------------"
          EOF

      - name: Change REDIS unix.sock configuration
        run: |
          scp -o StrictHostKeyChecking=no redis/redis-unix-sock/local-production-linux.json ubuntu@54.234.188.198:/home/ubuntu/redis-unix-sock/local-production-linux.json
          ssh -o StrictHostKeyChecking=no ubuntu@54.234.188.198 << 'EOF'
          sudo docker exec ds-ee-dev bash -c "
            sed -i 's/^port .*/port 0/' /etc/redis/redis.conf
            echo 'unixsocket /run/redis/redis-server.sock' >> /etc/redis/redis.conf
            echo 'unixsocketperm 777' >> /etc/redis/redis.conf
            service redis-server restart
          "
          echo "-------------------------------------"
          sudo docker exec ds-ee-dev redis-cli -s /run/redis/redis-server.sock ping
          echo "-------------------------------------"

          sudo docker cp /home/ubuntu/redis-unix-sock/local-production-linux.json ds-ee-dev:/etc/onlyoffice/documentserver/local-production-linux.json
          sudo docker exec ds-ee-dev cat /etc/onlyoffice/documentserver/local-production-linux.json
          sudo docker exec ds-ee-dev supervisorctl restart all
          sleep 10
          echo "-------------------------------------"
          curl -s https://oods.div-proxy.qa-onlyoffice.net/healthcheck
          echo "-------------------------------------"
          rm /home/ubuntu/redis-unix-sock/local-production-linux.json
          EOF

      - name: Smoke puppeteer API tests ONLYOFFICE-Docs EE
        run: |
          cd Dep.Tests/puppeteer/engine
          sed -i -E 's#"url": "https://[^/]+\.teamlab\.info/example"#"url": "https://oods.div-proxy.qa-onlyoffice.net/example"#' ../config_chrome_linux.json
          sed -i 's/"headless": false/"headless": true/' ../config_chrome_linux.json
          cat ../config_chrome_linux.json
          python3 run.py --prcache
          python3 run.py ../tests/desktop/word/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/spreadsheets/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/presentation/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/pdf/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/pdf-form/smoke/ --disable_animation --config_params puppeteerOptions.headless=true

      - name: Smoke puppeteer WOPI tests ONLYOFFICE-Docs EE
        run: |
          cd Dep.Tests/puppeteer/engine
          sed -i 's/"provider": *""/"provider": "wopi.js"/' ../config_chrome_linux.json
          sed -i -E 's#"url": "https://[^/]+\.teamlab\.info/example"#"url": "https://oods.div-proxy.qa-onlyoffice.net/example"#' ../providers/wopi/config.json
          cat ../config_chrome_linux.json
          cat ../providers/wopi/config.json
          python3 run.py --prcache
          python3 run.py ../tests/desktop/word/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/spreadsheets/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/presentation/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/pdf/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/pdf-form/smoke/ --disable_animation --config_params puppeteerOptions.headless=true

      - name: Logs work with REDIS and remove container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.234.188.198 << 'EOF'
          sudo docker logs -n 1000 ds-ee-dev
          sudo docker rm -fv ds-ee-dev
          EOF

      - name: Docker run ONLYOFFICE-Docs EE for test IOREDIS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.234.188.198 << 'EOF'
          sudo docker pull onlyoffice/4testing-documentserver-ee:${{ vars.ONLYOFFICE_VERSION }}.${{ vars.ONLYOFFICE_BUILD }}
          sudo docker run -itd -p 8080:80 -e WOPI_ENABLED=true --name ds-ee-dev onlyoffice/4testing-documentserver-ee:${{ vars.ONLYOFFICE_VERSION }}.${{ vars.ONLYOFFICE_BUILD }}
          sleep 120
          sudo docker exec ds-ee-dev supervisorctl start all
          echo "-------------------------------------"
          curl -s https://oods.div-proxy.qa-onlyoffice.net/healthcheck
          echo "-------------------------------------"
          EOF

      - name: Change IOREDIS unix.sock configuration
        run: |
          scp -o StrictHostKeyChecking=no redis/ioredis-unix-sock/local-production-linux.json ubuntu@54.234.188.198:/home/ubuntu/ioredis-unix-sock/local-production-linux.json
          ssh -o StrictHostKeyChecking=no ubuntu@54.234.188.198 << 'EOF'
          sudo docker exec ds-ee-dev bash -c "
            sed -i 's/^port .*/port 0/' /etc/redis/redis.conf
            echo 'unixsocket /run/redis/redis-server.sock' >> /etc/redis/redis.conf
            echo 'unixsocketperm 777' >> /etc/redis/redis.conf
            service redis-server restart
          "

          sudo docker cp /home/ubuntu/ioredis-unix-sock/local-production-linux.json ds-ee-dev:/etc/onlyoffice/documentserver/local-production-linux.json
          sudo docker exec ds-ee-dev cat /etc/onlyoffice/documentserver/local-production-linux.json
          sudo docker exec ds-ee-dev supervisorctl restart all
          sleep 10
          echo "-------------------------------------"
          curl -s https://oods.div-proxy.qa-onlyoffice.net/healthcheck
          echo "-------------------------------------"
          rm /home/ubuntu/ioredis-unix-sock/local-production-linux.json
          EOF

      - name: Smoke puppeteer API tests ONLYOFFICE-Docs EE
        run: |
          cd Dep.Tests/puppeteer/engine
          sed -i 's/"provider": *"wopi\.js"/"provider": ""/' ../config_chrome_linux.json
          cat ../config_chrome_linux.json
          python3 run.py --prcache
          python3 run.py ../tests/desktop/word/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/spreadsheets/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/presentation/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/pdf/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/pdf-form/smoke/ --disable_animation --config_params puppeteerOptions.headless=true

      - name: Smoke puppeteer WOPI tests ONLYOFFICE-Docs EE
        run: |
          cd Dep.Tests/puppeteer/engine
          sed -i 's/"provider": *""/"provider": "wopi.js"/' ../config_chrome_linux.json
          cat ../config_chrome_linux.json
          cat ../providers/wopi/config.json
          python3 run.py --prcache
          python3 run.py ../tests/desktop/word/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/spreadsheets/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/presentation/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/pdf/smoke/ --disable_animation --config_params puppeteerOptions.headless=true
          python3 run.py ../tests/desktop/pdf-form/smoke/ --disable_animation --config_params puppeteerOptions.headless=true

      - name: Logs work with IOREDIS and remove container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.234.188.198 << 'EOF'
          sudo docker logs -n 1000 ds-ee-dev
          sudo docker rm -fv ds-ee-dev
          EOF

      - name: Clean docker
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.234.188.198 << 'EOF'
          sudo docker system prune -af
          EOF