name: dev Redis unix.sock

on:
  schedule:
    - cron: '0 12 * * 3'  # Wednesday 15:00 MosÑow time (UTC+3)
  workflow_dispatch:

jobs:
  test-dev-Redis-unix-sock:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install prerequisites for puppeteer tests
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y
          google-chrome --version
          python3 --version
          pip3 --version
          node -v
          npm -v

          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan git.onlyoffice.com >> ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone git@git.onlyoffice.com:ONLYOFFICE-QA/Dep.Tests.git
          cd Dep.Tests
          sed -i 's/url=https:\/\/github.com\/ONLYOFFICE-data\/pp-files.git/url = git@github.com:ONLYOFFICE-data\/pp-files.git/' .gitmodules
          git submodule update --init puppeteer/files
          cd puppeteer/engine
          npm install
          cp ../config_chrome_linux.json ../config_chrome_linux.json.bak

      - name: Docker run ONLYOFFICE-Docs EE for test REDIS
        run: |
          sudo docker pull onlyoffice/4testing-documentserver-ee:${{ vars.ONLYOFFICE_VERSION }}.${{ vars.ONLYOFFICE_BUILD }}
          sudo docker run -itd -p 80:80 -e WOPI_ENABLED=true --name ds-redis-sock onlyoffice/4testing-documentserver-ee:${{ vars.ONLYOFFICE_VERSION }}.${{ vars.ONLYOFFICE_BUILD }}
          sleep 180
          sudo docker exec ds-redis-sock supervisorctl start ds:example

      - name: Get runner IP
        id: runner_ip
        run: |
          IP=$(ip route get 1 | awk '{print $7}')
          echo "RUNNER_IP=$IP" >> $GITHUB_ENV
          echo "Runner IP is $IP"

      - name: INFO about installed Package, must be ONLYOFFICE-Docs EE
        continue-on-error: true
        run: |
          sudo apt-get install jq -y

          echo "-------------healthcheck-------------"
          curl -s http://${RUNNER_IP}/healthcheck; echo
          echo "-------------DS services-------------"
          sudo docker exec ds-redis-sock supervisorctl status all
          echo "-------------healthcheck-------------"
          curl -s http://${RUNNER_IP}/healthcheck; echo
          echo "---------Installed packages----------"
          docker exec ds-redis-sock bash -c "dpkg -l | grep onlyoffice"
          echo "---------api.js from server----------"
          curl -s http://${RUNNER_IP}/web-apps/apps/api/documents/api.js | head -n 10
          echo "--------packageType must be 1--------"
          docker exec ds-redis-sock curl -s http://127.0.0.1/info/info.json | jq | grep -i -e buildVersion -e buildNumber -e packageType
          echo "-------------WOPI local--------------"
          output=$(curl -s http://${RUNNER_IP}/hosting/discovery)
          if echo "$output" | grep -q 'value='; then
            echo "$output" | grep -o 'value="[^"]*"' | head -n 5 | cut -c1-100
          else
            echo "$output"
          fi

      - name: Change REDIS unix.sock configuration
        run: |
          sudo docker exec ds-redis-sock bash -c "
            sed -i 's/^port .*/port 0/' /etc/redis/redis.conf
            echo 'unixsocket /run/redis/redis-server.sock' >> /etc/redis/redis.conf
            echo 'unixsocketperm 777' >> /etc/redis/redis.conf
            pkill -f 'redis-server'
          "
          sleep 10
          sudo docker exec ds-redis-sock service redis-server start

          echo "------------ Redis ping -------------"
          sudo docker exec ds-redis-sock redis-cli -s /run/redis/redis-server.sock ping
          echo "------------ Redis ps -------------"
          sudo docker exec ds-redis-sock ps -aux | grep -i redis

          sudo docker cp redis/redis-unix-sock/local-production-linux.json ds-redis-sock:/etc/onlyoffice/documentserver/local-production-linux.json
          echo "------------ local-production-linux.json -------------"
          sudo docker exec ds-redis-sock cat /etc/onlyoffice/documentserver/local-production-linux.json
          sudo docker exec ds-redis-sock supervisorctl restart all
          sleep 10
          echo "---------- ds healthcheck -----------"
          curl -s http://${RUNNER_IP}/healthcheck; echo

      - name: Smoke puppeteer API tests with REDIS
        continue-on-error: true
        run: |
          cd Dep.Tests/puppeteer/engine
          sed -i -E "s#\"url\": \"https://[^/]+\.teamlab\.info/example\"#\"url\": \"http://${RUNNER_IP}/example\"#" ../config_chrome_linux.json
          echo "-------------------------------------"
          cat ../config_chrome_linux.json
          echo "-------------------------------------"
          python3 run.py --suite daily --disable_animation --config_params puppeteerOptions.headless=true puppeteerOptions.channel=chrome --providers example

      - name: Smoke puppeteer WOPI tests with REDIS
        continue-on-error: true
        run: |
          cd Dep.Tests/puppeteer/engine
          echo "-------------------------------------"
          cat ../config_chrome_linux.json
          echo "-------------------------------------"
          python3 run.py --suite daily --disable_animation --config_params puppeteerOptions.headless=true puppeteerOptions.channel=chrome --providers wopi

      - name: Documentserver logs PUPPETEER TESTS and remove REDIS container
        run: |
          docker logs -n 1000 ds-redis-sock
          docker rm -fv ds-redis-sock

      - name: Docker run ONLYOFFICE-Docs EE for test IOREDIS
        run: |
          sudo docker pull onlyoffice/4testing-documentserver-ee:${{ vars.ONLYOFFICE_VERSION }}.${{ vars.ONLYOFFICE_BUILD }}
          sudo docker run -itd -p 80:80 -e WOPI_ENABLED=true --name ds-ioredis-sock onlyoffice/4testing-documentserver-ee:${{ vars.ONLYOFFICE_VERSION }}.${{ vars.ONLYOFFICE_BUILD }}
          sleep 180
          sudo docker exec ds-ioredis-sock supervisorctl start ds:example

      - name: INFO about installed Package, must be ONLYOFFICE-Docs EE
        continue-on-error: true
        run: |
          sudo apt-get install jq -y

          echo "-------------healthcheck-------------"
          curl -s http://${RUNNER_IP}/healthcheck; echo
          echo "-------------DS services-------------"
          sudo docker exec ds-ioredis-sock supervisorctl status all
          echo "-------------healthcheck-------------"
          curl -s http://${RUNNER_IP}/healthcheck; echo
          echo "---------Installed packages----------"
          docker exec ds-ioredis-sock bash -c "dpkg -l | grep onlyoffice"
          echo "---------api.js from server----------"
          curl -s http://${RUNNER_IP}/web-apps/apps/api/documents/api.js | head -n 10
          echo "--------packageType must be 1--------"
          docker exec ds-ioredis-sock curl -s http://127.0.0.1/info/info.json | jq | grep -i -e buildVersion -e buildNumber -e packageType
          echo "-------------WOPI local--------------"
          output=$(curl -s http://${RUNNER_IP}/hosting/discovery)
          if echo "$output" | grep -q 'value='; then
            echo "$output" | grep -o 'value="[^"]*"' | head -n 5 | cut -c1-100
          else
            echo "$output"
          fi

      - name: Change IOREDIS unix.sock configuration
        run: |
          sudo docker exec ds-ioredis-sock bash -c "
            sed -i 's/^port .*/port 0/' /etc/redis/redis.conf
            echo 'unixsocket /run/redis/redis-server.sock' >> /etc/redis/redis.conf
            echo 'unixsocketperm 777' >> /etc/redis/redis.conf
            pkill -f 'redis-server'
          "
          sleep 10
          sudo docker exec ds-ioredis-sock service redis-server start

          echo "------------ Redis ping -------------"
          sudo docker exec ds-ioredis-sock redis-cli -s /run/redis/redis-server.sock ping
          echo "------------ Redis ps -------------"
          sudo docker exec ds-ioredis-sock ps -aux | grep -i redis

          sudo docker cp redis/ioredis-unix-sock/local-production-linux.json ds-ioredis-sock:/etc/onlyoffice/documentserver/local-production-linux.json
          echo "------------ local-production-linux.json -------------"
          sudo docker exec ds-ioredis-sock cat /etc/onlyoffice/documentserver/local-production-linux.json
          sudo docker exec ds-ioredis-sock supervisorctl restart all
          sleep 10
          echo "---------- ds healthcheck -----------"
          curl -s http://${RUNNER_IP}/healthcheck; echo

      - name: Smoke puppeteer API tests with IOREDIS
        continue-on-error: true
        run: |
          cd Dep.Tests/puppeteer/engine
          sed -i -E "s#\"url\": \"https://[^/]+\.teamlab\.info/example\"#\"url\": \"http://${RUNNER_IP}/example\"#" ../config_chrome_linux.json
          echo "-------------------------------------"
          cat ../config_chrome_linux.json
          echo "-------------------------------------"
          python3 run.py --suite daily --disable_animation --config_params puppeteerOptions.headless=true puppeteerOptions.channel=chrome --providers example

      - name: Smoke puppeteer WOPI tests with IOREDIS
        continue-on-error: true
        run: |
          cd Dep.Tests/puppeteer/engine
          echo "-------------------------------------"
          cat ../config_chrome_linux.json
          echo "-------------------------------------"
          python3 run.py --suite daily --disable_animation --config_params puppeteerOptions.headless=true puppeteerOptions.channel=chrome --providers wopi

      - name: Documentserver logs PUPPETEER TESTS and remove IOREDIS container
        run: |
          sudo docker logs -n 1000 ds-ioredis-sock
          sudo docker rm -fv ds-ioredis-sock