name: dev DB Oracle

on:
  schedule:
    - cron: '0 12 * * 3'  # Wednesday 15:00 MosÑow time (UTC+3)
  workflow_dispatch:

jobs:
  oracle-test:
    runs-on: ubuntu-24.04
    services:
      oracledb:
        image: gvenzl/oracle-xe:21-slim
        env:
          ORACLE_PASSWORD: admin
          ORACLE_DATABASE: onlyoffice
          APP_USER: onlyoffice
          APP_USER_PASSWORD: onlyoffice
        ports:
          - 1521:1521

      onlyoffice:
        image: onlyoffice/4testing-documentserver-ee:${{ vars.ONLYOFFICE_VERSION }}.${{ vars.ONLYOFFICE_BUILD }}
        env:
          DB_TYPE: oracle
          DB_HOST: oracledb
          DB_PORT: 1521
          DB_NAME: onlyoffice
          DB_USER: onlyoffice
          DB_PWD: onlyoffice
          WOPI_ENABLED: true
          JWT_SECRET: MYSECRET
        ports:
          - 80:80

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: docker containers STATUS
        run: |
          docker ps -a

      - name: Wait for Oracle DB and ONLYOFFICE to be ready
        run: sleep 180

      - name: Define ONLYOFFICE container name
        run: |
          ONLYOFFICE_CONTAINER_NAME=$(docker ps -a --filter "ancestor=onlyoffice/4testing-documentserver-ee:${{ vars.ONLYOFFICE_VERSION }}.${{ vars.ONLYOFFICE_BUILD }}" --format "{{.Names}}")
          echo "Container name: $ONLYOFFICE_CONTAINER_NAME"
          echo "ONLYOFFICE_CONTAINER_NAME=$ONLYOFFICE_CONTAINER_NAME" >> $GITHUB_ENV

      - name: Define ORACLE container name
        run: |
          ORACLE_CONTAINER_NAME=$(docker ps -a --filter "ancestor=gvenzl/oracle-xe:21-slim" --format "{{.Names}}")
          echo "Container name: $ORACLE_CONTAINER_NAME"
          echo "ORACLE_CONTAINER_NAME=$ORACLE_CONTAINER_NAME" >> $GITHUB_ENV

      - name: Get runner IP
        id: runner_ip
        run: |
          IP=$(ip route get 1 | awk '{print $7}')
          echo "RUNNER_IP=$IP" >> $GITHUB_ENV
          echo "Runner IP is $IP"

      - name: ADD document, dummy_end_points and license for tests
        run: |
          docker exec $ONLYOFFICE_CONTAINER_NAME wget -O /var/www/onlyoffice/documentserver/sample.zip https://nct2.onlyoffice.com/s/y-3qCyC7GkMcYv8
          docker exec $ONLYOFFICE_CONTAINER_NAME unzip /var/www/onlyoffice/documentserver/sample.zip -d /var/www/onlyoffice/documentserver/
          docker cp performance-test/local-production-linux.json $ONLYOFFICE_CONTAINER_NAME:/etc/onlyoffice/documentserver/local-production-linux.json
          docker exec $ONLYOFFICE_CONTAINER_NAME supervisorctl restart ds:docservice
          docker exec $ONLYOFFICE_CONTAINER_NAME supervisorctl restart ds:converter
          docker exec $ONLYOFFICE_CONTAINER_NAME supervisorctl start ds:example

          cat <<'EOF' > license.lic
          ${{ secrets.LICENSE_KEY }}
          EOF
          docker cp license.lic $ONLYOFFICE_CONTAINER_NAME:/var/www/onlyoffice/Data/license.lic

      - name: CHECK document, dummy_end_points and license
        run: |
          echo '--- local-production-linux.json  ---'
          docker exec $ONLYOFFICE_CONTAINER_NAME cat /etc/onlyoffice/documentserver/local-production-linux.json
          echo '--- Sample.docx in documentserver ---'
          docker exec $ONLYOFFICE_CONTAINER_NAME ls /var/www/onlyoffice/documentserver/
          echo '--- license ---'
          docker exec $ONLYOFFICE_CONTAINER_NAME ls /var/www/onlyoffice/Data/

      - name: INFO about installed Package, must be ONLYOFFICE-Docs EE
        continue-on-error: true
        run: |
          sudo apt-get install jq -y

          echo "-------------healthcheck-------------"
          curl -s http://${RUNNER_IP}/healthcheck; echo
          echo "-------------DS services-------------"
          sudo supervisorctl status all
          echo "---------Installed packages----------"
          docker exec $ONLYOFFICE_CONTAINER_NAME bash -c "dpkg -l | grep onlyoffice"
          echo "---------api.js from server----------"
          curl -s http://${RUNNER_IP}/web-apps/apps/api/documents/api.js | head -n 10
          echo "--------packageType must be 1--------"
          docker exec $ONLYOFFICE_CONTAINER_NAME curl -s http://127.0.0.1/info/info.json | jq | grep -i -e buildVersion -e buildNumber -e packageType
          echo "-------------WOPI local--------------"
          output=$(curl -s http://${RUNNER_IP}/hosting/discovery)
          if echo "$output" | grep -q 'value='; then
            echo "$output" | grep -o 'value="[^"]*"' | head -n 5 | cut -c1-100
          else
            echo "$output"
          fi

      - name: Install pre-requisites for LOAD test
        run: |
          git clone https://github.com/ONLYOFFICE/document-server-stress-testing.git -b ${{ vars.K6_BRANCH }}
          cd document-server-stress-testing/K6/

          sed -i 's|"serverNameOrIp": "localhost"|"serverNameOrIp": "onlyoffice"|' save-changes-document-random-close.json
          sed -i 's|"documentUrl": "https://example.com/url-to-example-document"|"documentUrl": "http://onlyoffice/wopi/files/docid/contents"|' save-changes-document-random-close.json
          sed -i 's|"callbackUrl": "https://example.com/url-to-callback"|"callbackUrl": "http://onlyoffice/dummyCallback"|' save-changes-document-random-close.json
          sed -i 's|"jwtSecret": ""|"jwtSecret": "MYSECRET"|' save-changes-document-random-close.json

      - name: INFO about save-changes-document-random-close.json
        run: |
          echo "------ Updated json ------"
          cd document-server-stress-testing/K6/
          cat save-changes-document-random-close.json

      - name: Run K6 LOAD test
        continue-on-error: true
        working-directory: document-server-stress-testing/K6
        run: |
          docker run --rm \
            -u "$(id -u):$(id -g)" \
            --network ${{ job.services.onlyoffice.network }} \
            -v "$(pwd)":/k6 \
            grafana/k6 run /k6/save-changes-document-random-close.js \
            --quiet \
            -s "1m:500" -s "9m:500"

      - name: Documentserver logs LOAD test
        run: |
          docker logs -n 1000 $ONLYOFFICE_CONTAINER_NAME

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
  
      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install prerequisites for puppeteer tests
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y
          google-chrome --version
          python3 --version
          pip3 --version
          node -v
          npm -v

          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan git.onlyoffice.com >> ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone git@git.onlyoffice.com:ONLYOFFICE-QA/Dep.Tests.git
          cd Dep.Tests
          sed -i 's/url=https:\/\/github.com\/ONLYOFFICE-data\/pp-files.git/url = git@github.com:ONLYOFFICE-data\/pp-files.git/' .gitmodules
          git submodule update --init puppeteer/files
          cd puppeteer/engine
          npm install
          cp ../config_chrome_linux.json ../config_chrome_linux.json.bak

      - name: Smoke puppeteer API tests
        continue-on-error: true
        run: |
          cd Dep.Tests/puppeteer/engine
          sed -i -E "s#\"url\": \"https://[^/]+\.teamlab\.info/example\"#\"url\": \"http://${RUNNER_IP}/example\"#" ../config_chrome_linux.json
          echo "-------------------------------------"
          cat ../config_chrome_linux.json
          echo "-------------------------------------"
          python3 run.py --suite daily --disable_animation --config_params puppeteerOptions.headless=true --providers example

      - name: Documentserver logs PUPPETEER TEST
        run: |
          docker logs -n 1000 $ONLYOFFICE_CONTAINER_NAME