name: release DEB x64

on:
  workflow_dispatch:

jobs:
  test-install-deb-x64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install prerequisites for puppeteer tests
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y
          google-chrome --version
          python3 --version
          pip3 --version
          node -v
          npm -v

          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan git.onlyoffice.com >> ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone git@git.onlyoffice.com:ONLYOFFICE-QA/Dep.Tests.git
          cd Dep.Tests
          sed -i 's/url=https:\/\/github.com\/ONLYOFFICE-data\/pp-files.git/url = git@github.com:ONLYOFFICE-data\/pp-files.git/' .gitmodules
          git submodule update --init puppeteer/files
          cd puppeteer/engine
          npm install
          cp ../config_chrome_linux.json ../config_chrome_linux.json.bak

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      - name: Create EC2 Instance
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0b6c6ebed2801a5cb \
            --instance-type t2.medium \
            --key-name demin \
            --security-groups AllPortsOpened \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=demin_release-deb-x64}]' \
            --block-device-mappings '[{"DeviceName":"/dev/sda1","Ebs":{"VolumeSize":50,"VolumeType":"gp3"}}]' \
            --query "Instances[0].InstanceId" --output text)

          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          echo "Waiting for instance to start..."
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID

      - name: Get EC2 Public IP
        run: |
          IP=$(aws ec2 describe-instances \
            --instance-ids ${{ env.INSTANCE_ID }} \
            --query "Reservations[].Instances[].PublicIpAddress" --output text)
          echo "EC2 Public IP: $IP"
          echo "EC2_IP=$IP" >> $GITHUB_ENV

      - name: Wait for SSH to be Ready
        run: sleep 60

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Upgrade DEB packages
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          sudo apt-get update
          sudo apt-get upgrade -y
          EOF

      - name: Reboot EC2 Instance
        run: aws ec2 reboot-instances --instance-ids ${{ env.INSTANCE_ID }}

      - name: Wait for instance to reboot
        run: sleep 120

      - name: Install ONLYOFFICE-Docs EE
        continue-on-error: true
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          sudo apt-get install postgresql -y
          sudo -i -u postgres psql -c "CREATE USER onlyoffice WITH PASSWORD 'onlyoffice';"
          sudo -i -u postgres psql -c "CREATE DATABASE onlyoffice OWNER onlyoffice;"
          echo onlyoffice-documentserver-ee onlyoffice/db-pwd select onlyoffice | sudo debconf-set-selections

          sudo apt-get install redis-server -y

          sudo apt-get install rabbitmq-server -y

          mkdir -p -m 700 ~/.gnupg
          curl -fsSL https://download.onlyoffice.com/GPG-KEY-ONLYOFFICE | gpg --no-default-keyring --keyring gnupg-ring:/tmp/onlyoffice.gpg --import
          chmod 644 /tmp/onlyoffice.gpg
          sudo chown root:root /tmp/onlyoffice.gpg
          sudo mv /tmp/onlyoffice.gpg /usr/share/keyrings/onlyoffice.gpg

          echo "deb [signed-by=/usr/share/keyrings/onlyoffice.gpg] https://download.onlyoffice.com/repo/debian squeeze main" | sudo tee /etc/apt/sources.list.d/onlyoffice.list

          sudo apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer -y

          echo onlyoffice-documentserver-ee onlyoffice/wopi-enabled boolean true | sudo debconf-set-selections
          sudo apt-get install onlyoffice-documentserver-ee -y
          sudo systemctl start ds-example
          EOF

      - name: Info about installed Package, must be ONLYOFFICE-Docs EE
        continue-on-error: true
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          sudo apt-get install jq -y
          echo "-------------healthcheck-------------"
          sleep 10
          curl -s http://${{ env.EC2_IP }}/healthcheck; echo
          echo "-------------DS services-------------"
          sudo systemctl list-unit-files --type=service | grep ds-
          echo "---------Installed packages----------"
          sudo dpkg-query -l | grep onlyoffice-documentserver
          echo "---------api.js from server----------"
          curl -s http://127.0.0.1/web-apps/apps/api/documents/api.js | head -n 10
          echo "--------packageType--------"
          curl -s http://127.0.0.1:8000/info/info.json | jq | grep -i -e buildVersion -e buildNumber -e packageType
          echo "-------------WOPI local--------------"
          curl -s http://127.0.0.1/hosting/discovery | tail -c 150; echo
          echo "------------WOPI external------------"
          curl -s http://${{ env.EC2_IP }}/hosting/discovery | tail -c 150; echo
          echo "-------------DS-example-------------"
          sudo systemctl start ds-example
          sudo systemctl status ds-example
          EOF

      - name: Smoke puppeteer API tests ONLYOFFICE-Docs EE
        continue-on-error: true
        run: |
          cd Dep.Tests/puppeteer/engine
          sed -i -E "s#\"url\": \"https://[^/]+\.teamlab\.info/example\"#\"url\": \"http://${{ env.EC2_IP }}/example\"#" ../config_chrome_linux.json
          echo "-------------------------------------"
          cat ../config_chrome_linux.json
          echo "-------------------------------------"
          python3 run.py --suite daily --disable_animation --config_params puppeteerOptions.headless=true puppeteerOptions.channel=chrome --providers example

      - name: Smoke puppeteer WOPI tests ONLYOFFICE-Docs EE
        continue-on-error: true
        run: |
          cd Dep.Tests/puppeteer/engine
          echo "-------------------------------------"
          cat ../config_chrome_linux.json
          echo "-------------------------------------"
          python3 run.py --suite daily --disable_animation --config_params puppeteerOptions.headless=true puppeteerOptions.channel=chrome --providers wopi

      - name: Documentserver logs ONLYOFFICE-Docs EE
        continue-on-error: true
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          sudo tail -n 1000 /var/log/onlyoffice/documentserver/converter/out.log /var/log/onlyoffice/documentserver/converter/err.log  /var/log/onlyoffice/documentserver/docservice/out.log  /var/log/onlyoffice/documentserver/docservice/err.log  /var/log/onlyoffice/documentserver/metrics/out.log /var/log/onlyoffice/documentserver/metrics/err.log /var/log/onlyoffice/documentserver/nginx.error.log  /var/log/onlyoffice/documentserver-example/out.log /var/log/onlyoffice/documentserver/adminpanel/out.log /var/log/onlyoffice/documentserver/adminpanel/err.log
          EOF

      - name: Remove ONLYOFFICE-Docs EE
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          printf "n/n" | sudo apt-get purge onlyoffice-documentserver* -y
          sudo rm -rvf /etc/onlyoffice /var/www/onlyoffice /var/log/onlyoffice
          EOF

      - name: Reboot EC2 Instance
        run: aws ec2 reboot-instances --instance-ids ${{ env.INSTANCE_ID }}

      - name: Wait for instance to reboot
        run: sleep 60

      - name: Install ONLYOFFICE-Docs DE
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          echo onlyoffice-documentserver-de onlyoffice/db-pwd select onlyoffice | sudo debconf-set-selections
          echo onlyoffice-documentserver-de onlyoffice/wopi-enabled boolean true | sudo debconf-set-selections
          printf "n/n" | sudo apt-get install onlyoffice-documentserver-de -y
          sudo systemctl start ds-example
          EOF

      - name: Info about installed Package, must be ONLYOFFICE-Docs DE
        continue-on-error: true
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          echo "-------------healthcheck-------------"
          sleep 10
          curl -s http://${{ env.EC2_IP }}/healthcheck; echo
          echo "-------------DS services-------------"
          sudo systemctl list-unit-files --type=service | grep ds-
          echo "---------Installed packages----------"
          sudo dpkg-query -l | grep onlyoffice-documentserver
          echo "---------api.js from server----------"
          curl -s http://127.0.0.1/web-apps/apps/api/documents/api.js | head -n 10
          echo "--------packageType--------"
          curl -s http://127.0.0.1:8000/info/info.json | jq | grep -i -e buildVersion -e buildNumber -e packageType
          echo "-------------WOPI local--------------"
          curl -s http://127.0.0.1/hosting/discovery | tail -c 150; echo
          echo "------------WOPI external------------"
          curl -s http://${{ env.EC2_IP }}/hosting/discovery | tail -c 150; echo
          echo "-------------DS-example-------------"
          sudo systemctl start ds-example
          sudo systemctl status ds-example
          EOF

      - name: Smoke puppeteer API tests ONLYOFFICE-Docs DE
        continue-on-error: true
        run: |
          cd Dep.Tests/puppeteer/engine
          echo "-------------------------------------"
          cat ../config_chrome_linux.json
          echo "-------------------------------------"
          python3 run.py --suite daily --disable_animation --config_params puppeteerOptions.headless=true puppeteerOptions.channel=chrome --providers example

      - name: Smoke puppeteer WOPI tests ONLYOFFICE-Docs DE
        continue-on-error: true
        run: |
          cd Dep.Tests/puppeteer/engine
          echo "-------------------------------------"
          cat ../config_chrome_linux.json
          echo "-------------------------------------"
          python3 run.py --suite daily --disable_animation --config_params puppeteerOptions.headless=true puppeteerOptions.channel=chrome --providers wopi

      - name: Documentserver logs ONLYOFFICE-Docs DE
        continue-on-error: true
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          sudo tail -n 1000 /var/log/onlyoffice/documentserver/converter/out.log /var/log/onlyoffice/documentserver/converter/err.log  /var/log/onlyoffice/documentserver/docservice/out.log  /var/log/onlyoffice/documentserver/docservice/err.log  /var/log/onlyoffice/documentserver/metrics/out.log /var/log/onlyoffice/documentserver/metrics/err.log /var/log/onlyoffice/documentserver/nginx.error.log  /var/log/onlyoffice/documentserver-example/out.log /var/log/onlyoffice/documentserver/adminpanel/out.log /var/log/onlyoffice/documentserver/adminpanel/err.log
          EOF

      - name: Remove ONLYOFFICE-Docs DE
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          printf "n/n" | sudo apt-get purge onlyoffice-documentserver* -y
          sudo rm -rvf /etc/onlyoffice /var/www/onlyoffice /var/log/onlyoffice
          EOF

      - name: Reboot EC2 Instance
        run: aws ec2 reboot-instances --instance-ids ${{ env.INSTANCE_ID }}

      - name: Wait for instance to reboot
        run: sleep 60

      - name: Install ONLYOFFICE-Docs CE
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          echo onlyoffice-documentserver onlyoffice/db-pwd select onlyoffice | sudo debconf-set-selections
          echo onlyoffice-documentserver onlyoffice/wopi-enabled boolean true | sudo debconf-set-selections
          printf "n/n" | sudo apt-get install onlyoffice-documentserver -y
          sudo systemctl start ds-example
          EOF

      - name: Info about installed Package, must be ONLYOFFICE-Docs CE
        continue-on-error: true
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          echo "-------------healthcheck-------------"
          sleep 10
          curl -s http://${{ env.EC2_IP }}/healthcheck; echo
          echo "-------------DS services-------------"
          sudo systemctl list-unit-files --type=service | grep ds-
          echo "---------Installed packages----------"
          sudo dpkg-query -l | grep onlyoffice-documentserver
          echo "---------api.js from server----------"
          curl -s http://127.0.0.1/web-apps/apps/api/documents/api.js | head -n 10
          echo "--------packageType--------"
          curl -s http://127.0.0.1:8000/info/info.json | jq | grep -i -e buildVersion -e buildNumber -e packageType
          echo "-------------WOPI local--------------"
          curl -s http://127.0.0.1/hosting/discovery | tail -c 150; echo
          echo "------------WOPI external------------"
          curl -s http://${{ env.EC2_IP }}/hosting/discovery | tail -c 150; echo
          echo "-------------DS-example-------------"
          sudo systemctl start ds-example
          sudo systemctl status ds-example
          EOF

      - name: Smoke puppeteer API tests ONLYOFFICE-Docs CE
        continue-on-error: true
        run: |
          cd Dep.Tests/puppeteer/engine
          echo "-------------------------------------"
          cat ../config_chrome_linux.json
          echo "-------------------------------------"
          python3 run.py --suite daily --disable_animation --config_params puppeteerOptions.headless=true puppeteerOptions.channel=chrome --providers example

      - name: Smoke puppeteer WOPI tests ONLYOFFICE-Docs CE
        continue-on-error: true
        run: |
          cd Dep.Tests/puppeteer/engine
          echo "-------------------------------------"
          cat ../config_chrome_linux.json
          echo "-------------------------------------"
          python3 run.py --suite daily --disable_animation --config_params puppeteerOptions.headless=true puppeteerOptions.channel=chrome --providers wopi

      - name: Documentserver logs ONLYOFFICE-Docs CE
        continue-on-error: true
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          sudo tail -n 1000 /var/log/onlyoffice/documentserver/converter/out.log /var/log/onlyoffice/documentserver/converter/err.log  /var/log/onlyoffice/documentserver/docservice/out.log  /var/log/onlyoffice/documentserver/docservice/err.log  /var/log/onlyoffice/documentserver/metrics/out.log /var/log/onlyoffice/documentserver/metrics/err.log /var/log/onlyoffice/documentserver/nginx.error.log  /var/log/onlyoffice/documentserver-example/out.log /var/log/onlyoffice/documentserver/adminpanel/out.log /var/log/onlyoffice/documentserver/adminpanel/err.log
          EOF

      - name: Remove ONLYOFFICE-Docs CE
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << EOF
          printf "n/n" | sudo apt-get purge onlyoffice-documentserver* -y
          sudo rm -rvf /etc/onlyoffice /var/www/onlyoffice /var/log/onlyoffice
          EOF

      - name: Delete EC2 Instance
        run: |
          aws ec2 terminate-instances --instance-ids ${{ env.INSTANCE_ID }}
          aws ec2 wait instance-terminated --instance-ids ${{ env.INSTANCE_ID }}
